name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: |
            Please refer to the [release notes](https://github.com/WIKA-Group/javascript_parsers?tab=readme-ov-file#release-notes).

      - name: Upload binaries to release
        if: steps.create_release.outcome == 'success'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: parsers.zip
          asset_name: wika_javascript_parsers_${{ github.ref_name }}.zip
          tag: ${{ github.ref_name }}
          overwrite: true

      - name: Release parsers and raw parsers npm package
        if: steps.create_release.outcome == 'success'
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
